version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db-2
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: rest_with_spring_bot_vieira
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
